name: "package_recordings"
root_directory: "/home/bobby/repos/latent-neural-dynamics-modeling"
data_directory: "{root_directory}/data"
save_directory: "{root_directory}/resampled_recordings"
logger_directory: "{root_directory}/logs"
participants_table_name: "participants.tsv"
participants_intermediate_table_name: "participants_2"
output_participants_table_name: "participants_at_60Hz_scaled_1e6_all_bands_raw_05_28"
ieeg_process:
  resampled_dir: "{save_directory}/resampled_mat_recordings"
  chunk_margin: 2
  resampled_freq: 60
  notch_freqs: []
  scale_factor: 1e6
  raw_bands:
    raw: [0.5, 28]
    delta_raw: [0.5, 4]
  envelope_bands:
    theta_env: [4, 8]
    alpha_env: [8, 12]
    lowbeta_env: [12, 16]
    beta_env: [16, 20]
    highbeta_env: [20, 28]