name: "package_recordings"
root_directory: "/home/bobby/repos/latent-neural-dynamics-modeling"
data_directory: "{root_directory}/data"
save_directory: "{root_directory}/resampled_recordings"
logger_directory: "{root_directory}/logs"
participants_table_name: "participants.tsv"
participants_intermediate_table_name: "participants_2"
output_participants_table_name: "participants_at_60Hz_scaled_1e6_full_features"
ieeg_process:
  resampled_dir: "{save_directory}/resampled_mat_recordings"
  chunk_margin: 2
  resampled_freq: 60
  notch_freqs: []
  scale_factor: 1e6
  raw_bands:
    lmp: [0.5, 5]
  envelope_bands:
    theta: [5, 8]
    alpha: [8, 12]
    lowbeta: [12, 24]
    highbeta: [24, 34]
    gamma: [34, 56]