sessions:
  PDI1_S2:
    ecog:
      target_K: 8
      n1: 10
      nx: 150
    laplacian:
      target_K: 8
      n1: 10
      nx: 75
  PDI1_S4:
    ecog:
      target_K: 8
      n1: 10
      nx: 100
    laplacian:
      target_K: 8
      n1: 10
      nx: 80
  PDI4_S2:
    ecog:
      target_K: 8
      n1: 7
      nx: 150
    laplacian:
      target_K: 8
      n1: 7
      nx: 60
  PDI4_S3:
    ecog:
      target_K: 8
      n1: 15
      nx: 150
    laplacian:
      target_K: 8
      n1: 10
      nx: 55
common:
  i: 35
  max_eigenvalue: null
  backward_kalman: false
  dbs_conditions:
  - both
thresholds:
  n1_relative_to_peak: 0.05
  nx_cumulative_energy: 0.95
