model:
  name: "varma_PDI4_S3_dbs_on_log_power"
  p: 20
  q: 1
  long_ar_lags: 30
  ridge_alpha: 1.0
  stabilize_roots: true
  max_root: 0.999
  sample_future_ma_errors: true
  time_first: true
  fast: false
  reuse_splits: true
  forecast:
    m: 2
    history: 5

data:
  root: "resampled_recordings/participants_at_80Hz_scaled_1e6_log"
  participant: "PDI4"
  session: "3"
  blocks: "all"
  channels:
    neural_input: [
      "ECOG_1_highbeta_log_power",
      "LFP_13_highbeta_log_power",
      "LFP_14_delta_log_power",
      "ECOG_1_delta_log_power",
      "LFP_9_delta_log_power",
      "LFP_12_alpha_log_power",
      "LFP_12_delta_log_power",
      "ECOG_2_highbeta_log_power",
      "LFP_11_theta_log_power",
      "LFP_9_alpha_log_power"
    ]
    output_type: "behavioral"
    output: [
      "tracing_velocity_y",
      "tracing_velocity_x",
      "tracing_jerk_x"
    ]
    input_lag: null
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 80
  dbs_condition: "on"
  jitter: 0

results:
  save_dir: "results/{model.name}"
  log_dir: "{results.save_dir}/logs"
  checkpoint_dir: "checkpoints"
