model:
  name: "varma_PDI2_S2"
  p: 20
  q: 1
  long_ar_lags: 30
  time_first: true
  fast: false
  reuse_splits: true
  forecast:
    m: 2
    history: 5

data:
  root: "resampled_recordings/participants_at_80Hz_scaled_1e6_log"
  participant: "PDI2"
  session: "2"
  blocks: "all"
  channels:
    neural_input: [
      "ECOG_3_highbeta_log_power",
      "ECOG_4_highbeta_log_power",
      "ECOG_4_lowbeta_log_power",
      "ECOG_4_theta_log_power",
      "ECOG_4_beta_log_power",
      "ECOG_3_beta_log_power",
      "ECOG_3_lowbeta_log_power",
      "LFP_11_delta_log_power",
      "ECOG_4_alpha_log_power",
      "ECOG_3_alpha_log_power"
    ]
    output_type: "behavioral"
    output: [
      "tracing_velocity_x",
      "tracing_acceleration_y",
      "tracing_acceleration_magnitude",
      "tracing_jerk_y",
      "tracing_jerk_magnitude"
    ]
    input_lag: null
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 80
  dbs_condition: "both"
  jitter: 0

results:
  save_dir: "results/{model.name}"
  log_dir: "{results.save_dir}/logs"
  checkpoint_dir: "checkpoints"
