model:
  name: "varma_PDI3_S4_dbs_both_narrow_band"
  p: 20
  q: 1
  long_ar_lags: 30
  time_first: true
  fast: false
  reuse_splits: false
  forecast:
    m: 2
    history: 5

data:
  root: "resampled_recordings/participants_at_80Hz_scaled_1e6_narrow_band"
  participant: "PDI3"
  session: "4"
  blocks: "all"
  channels:
    neural_input: [
      "LFP_15_lowbeta_raw",
      "ECOG_1_beta_raw",
      "ECOG_2_highbeta_raw",
      "ECOG_4_beta_raw",
      "LFP_14_lowbeta_raw",
      "ECOG_2_theta_raw",
      "LFP_13_lowbeta_raw",
      "LFP_12_highbeta_raw",
      "LFP_10_highbeta_raw",
      "LFP_9_highbeta_raw",
      "LFP_14_alpha_raw",
      "LFP_14_beta_raw",
      "ECOG_1_theta_raw",
      "LFP_11_highbeta_raw",
      "LFP_13_delta_raw",
      "ECOG_4_delta_raw",
      "ECOG_2_beta_raw",
      "ECOG_2_delta_raw",
      "LFP_15_beta_raw",
      "LFP_16_lowbeta_raw"
    ]
    output_type: "behavioral"
    output: [
      "tracing_velocity_y",
      "tracing_acceleration_x",
      "tracing_jerk_y",
      "tracing_jerk_magnitude"
    ]
    input_lag: null
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 80
  dbs_condition: "both"
  jitter: 0

results:
  save_dir: "results/{model.name}"
  log_dir: "{results.save_dir}/logs"
  checkpoint_dir: "checkpoints"
