model:
  name: psid_behavioral_PDI4_3_nx_150_n15_i100_dbs_off_200Hz_narrow_band_mrmr8
  nx: 150
  n1: 15
  i: 100
  time_first: true
  fast: false
  reuse_splits: false
  max_eigenvalue: 0.9999
  forecast:
    m: 2
    history: 5
data:
  root: resampled_recordings/participants_at_200Hz_scaled_1e6_narrow_band
  participant: PDI4
  session: '3'
  blocks: all
  channels:
    neural_input:
    - ECOG_2_gamma_30_35_raw
    - ECOG_4_theta_4_8_raw
    - ECOG_1_theta_4_8_raw
    - ECOG_2_gamma_70_75_raw
    - ECOG_2_beta_17_22_raw
    - ECOG_3_alpha_8_12_raw
    - ECOG_3_theta_4_8_raw
    - ECOG_3_gamma_40_45_raw
    output_type: behavioral
    output:
    - tracing_velocity_x
    - tracing_acceleration_magnitude
  split:
    within_session_split: true
  batch_size: 32
  sampling_frequency: 200
  dbs_condition: 'off'
results:
  save_dir: results/psid_behavioral_PDI4_3_nx_150_n15_i100_dbs_off_200Hz_narrow_band_mrmr8
  log_dir: results/psid_behavioral_PDI4_3_nx_150_n15_i100_dbs_off_200Hz_narrow_band_mrmr8/logs
  checkpoint_dir: checkpoints
