model:
  name: psid_grid_search_PDI2_S2_raw_env
  i: 80
  time_first: true
  reuse_splits: true
  forecast:
    m: 2
    history: 5
  grid_search:
    nx:
    - 15
    - 20
    - 25
    - 30
    - 40
    n1:
    - 2
    - 4
    - 8
    - 12
    - 1e-5
    - 1e-4
    - 1e-3
    - 1e-3
    - 1e-2
    backward_kalman:
    - true
    rescale_states:
    - true
    max_eigenvalue:
    - 0.995
    neural_bands:
    - - ECOG_1_delta_raw
      - ECOG_1_theta_raw
      - ECOG_1_alpha_raw
      - ECOG_1_lowbeta_env
      - ECOG_1_beta_env
      - ECOG_1_highbeta_env
      - ECOG_2_delta_raw
      - ECOG_2_theta_raw
      - ECOG_2_alpha_raw
      - ECOG_2_lowbeta_env
      - ECOG_2_beta_env
      - ECOG_2_highbeta_env
      - ECOG_3_delta_raw
      - ECOG_3_theta_raw
      - ECOG_3_alpha_raw
      - ECOG_3_lowbeta_env
      - ECOG_3_beta_env
      - ECOG_3_highbeta_env
      - ECOG_4_delta_raw
      - ECOG_4_theta_raw
      - ECOG_4_alpha_raw
      - ECOG_4_lowbeta_env
      - ECOG_4_beta_env
      - ECOG_4_highbeta_env
    behavioral_outputs:
    - - tracing_velocity_x
      - tracing_acceleration_y
      - tracing_acceleration_magnitude
      - tracing_jerk_y
      - tracing_jerk_magnitude
data:
  root: resampled_recordings/participants_at_80Hz_scaled_1e6_narrow_band
  participant: PDI2
  session: '2'
  blocks: all
  channels:
    neural_input:
    - ECOG_1_delta_raw
    - ECOG_1_theta_raw
    - ECOG_1_alpha_raw
    - ECOG_1_lowbeta_env
    - ECOG_1_beta_env
    - ECOG_1_highbeta_env
    - ECOG_2_delta_raw
    - ECOG_2_theta_raw
    - ECOG_2_alpha_raw
    - ECOG_2_lowbeta_env
    - ECOG_2_beta_env
    - ECOG_2_highbeta_env
    - ECOG_3_delta_raw
    - ECOG_3_theta_raw
    - ECOG_3_alpha_raw
    - ECOG_3_lowbeta_env
    - ECOG_3_beta_env
    - ECOG_3_highbeta_env
    - ECOG_4_delta_raw
    - ECOG_4_theta_raw
    - ECOG_4_alpha_raw
    - ECOG_4_lowbeta_env
    - ECOG_4_beta_env
    - ECOG_4_highbeta_env
    output_type: behavioral
    output:
    - tracing_velocity_x
    - tracing_acceleration_y
    - tracing_acceleration_magnitude
    - tracing_jerk_y
    - tracing_jerk_magnitude
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 80
  dbs_condition: both
results:
  save_dir: results/psid_grid_search_raw_env
  log_dir: '{results.save_dir}/logs'
  checkpoint_dir: checkpoints
