model:
  name: "dpad_neural_all_blocks_dbs_both"
  nx: 8  
  n1: 4  
  method_code: "DPAD_uAKCzCy2HL128U" 
  epochs: 2500
  forecast:
    m: 1  
    history: 2  

data:
  root: "resampled_recordings/participants_at_60Hz_scaled_1e6" 
  participant: "PDI1"
  session: "2"
  blocks: "all"
  preprocess: true
  channels:
    is_behavioral_neural: true
    input: ["ECOG_1"] 
    output: ["ECOG_4"]
    input_lag: 1    
  split:
    within_session_split: true
    train: 0.6  
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 60
  dbs_condition: "both"

results:
  save_dir: "results/{model.name}"
  log_dir: "{results.save_dir}/logs"
  checkpoint_dir: "checkpoints"
