model:
  name: "dpad_behavioral_raw_recordings"
  nx: 15  
  n1: 4 
  method_code: "DPAD_CNN_uAKCzCy2HL128U"
  model_timestamp: "20260208_130006"
  epochs: 3000
  fast: false
  
  # steps_ahead: [1, 2, 3, 4]
  # steps_ahead_loss_weights: [1.0, 1.0, 1.0, 1.0]

  steps_ahead: [1]
  steps_ahead_loss_weights: [1.0]

  forecast:
    m: 2  
    history: 5

data:
  root: "resampled_recordings/participants_at_60Hz_scaled_1e6_raw_05_30" 
  participant: "PDI4"
  session: "3"
  blocks: "all"
  channels:
    neural_input: [
      "ECOG_1_raw", "ECOG_2_raw", "ECOG_3_raw", "ECOG_4_raw"
    ]
    output_type: "behavioral"
    output: ["tracing_velocity_y", "tracing_acceleration_y"]
    input_lag: null
  split:
    within_session_split: true
    train: 0.8
    val: 0.1
    test: 0.1
    min_train_epochs: 50
  batch_size: 256
  sampling_frequency: 60
  dbs_condition: "both"
  jitter: 0

results:
  save_dir: "results/{model.name}"
  log_dir: "{results.save_dir}/logs"
  checkpoint_dir: "checkpoints"
