data:
  batch_size: 32
  blocks: all
  channels:
    input_lag: null
    neural_input:
    - ECOG_1_delta_raw
    - ECOG_2_delta_raw
    - ECOG_3_delta_raw
    - ECOG_4_delta_raw
    - ECOG_1_theta_env
    - ECOG_2_theta_env
    - ECOG_3_theta_env
    - ECOG_4_theta_env
    - ECOG_1_alpha_env
    - ECOG_2_alpha_env
    - ECOG_3_alpha_env
    - ECOG_4_alpha_env
    - ECOG_1_lowbeta_env
    - ECOG_2_lowbeta_env
    - ECOG_3_lowbeta_env
    - ECOG_4_lowbeta_env
    - ECOG_1_beta_env
    - ECOG_2_beta_env
    - ECOG_3_beta_env
    - ECOG_4_beta_env
    - ECOG_1_highbeta_env
    - ECOG_2_highbeta_env
    - ECOG_3_highbeta_env
    - ECOG_4_highbeta_env
    output:
    - tracing_velocity_x
    - tracing_velocity_y
    - tracing_velocity_magnitude
    - tracing_acceleration_x
    - tracing_acceleration_y
    - tracing_acceleration_magnitude
    - tracing_jerk_x
    - tracing_jerk_y
    - tracing_jerk_magnitude
    output_type: behavioral
  dbs_condition: 'off'
  jitter: 0
  participant: PDI2
  root: resampled_recordings/participants_at_60Hz_scaled_1e6_all_bands_raw_05_28
  sampling_frequency: 60
  session: '2'
  split:
    min_train_epochs: 50
    test: 0.2
    train: 0.6
    val: 0.2
    within_session_split: true
model:
  alpha_Q: 1e-3
  alpha_R: 1e-2
  backward_kalman: true
  fast: false
  forecast:
    history: 5
    m: 2
  i: 80
  max_eigenvalue: 0.995
  n1: 12
  name: psid_behavioral_PDI2_2_nx20_n12_i80_dbs_off
  nx: 20
  rescale_states: true
  reuse_splits: true
  time_first: true
results:
  checkpoint_dir: checkpoints
  log_dir: '{results.save_dir}/logs'
  save_dir: results/{model.name}
