model:
  name: null # Model name
  nx: null # Total latent dimensions
  n1: null # Behavior-prioritized latent dimensions
  i: null # Input dimensions
  time_first: null # Boolean
  backward_kalman: null # Boolean
  augment_x_with_z_noise: null # Boolean
  forecast:
    m: null # Number of seconds to forecast
    history: null # Number of seconds of history to use for forecasting

data:
  root: null # Root directory for data
  participant: null # Participant ID
  session: null # Session ID
  blocks: "all" # Blocks to use or all the blocks as string "all"
  channels:
    is_behavioral_neural: null # Boolean
    neural_input: [] # Y channels
    output: [] # Z channels
  split:
    within_session_split: null # Boolean
    train: 0.6 # Proportion of data to use for training
    val: 0.2 # Proportion of data to use for validation
    test: 0.2 # Proportion of data to use for testing
    min_train_epochs: 50 # Minimum number of epochs to train for
  batch_size: 32 # Batch size for training
  sampling_frequency: null # Sampling frequency of the data
  dbs_condition: "both" # Options: "on", "off", "both"

results:
  save_dir: "results/{model.name}" # Directory for saving results
  log_dir: "{results.save_dir}/logs" # Directory for logging
  checkpoint_dir: "checkpoints" # Directory for saving checkpoints