model:
  name: "psid_SEARCH_alpha"
  nx: 10
  n1: 9
  i: 20
  time_first: true
  fast: true
  reuse_splits: true
  Q_scale: 20.0
  R_scale: 20.0
  S_scale: 20.0
  forecast:
    m: 1 
    history: 2 

data:
  root: "resampled_recordings/participants_at_60Hz_scaled_1e6_full_features" 
  participant: "PDI1"
  session: "2"
  blocks: "all"
  channels:
    is_behavioral_neural: false
    neural_input: [
      "LFP_1_alpha", "LFP_2_alpha", "LFP_3_alpha", "LFP_4_alpha", "LFP_5_alpha", "LFP_6_alpha", "LFP_7_alpha", "LFP_8_alpha",
      "LFP_9_alpha", "LFP_10_alpha", "LFP_11_alpha", "LFP_12_alpha", "LFP_13_alpha", "LFP_14_alpha", "LFP_15_alpha", "LFP_16_alpha",
      "ECOG_1_alpha", "ECOG_2_alpha", "ECOG_3_alpha", "ECOG_4_alpha"
    ]
    output_type: "behavioral"
    output: [
      "tracing_velocity_x", "tracing_velocity_y",
      "tracing_velocity_cos", "tracing_velocity_sin",
      "tracing_acceleration_x", "tracing_acceleration_y",
      "tracing_acceleration_cos", "tracing_acceleration_sin",
      "tracing_jerk_x", "tracing_jerk_y",
      "tracing_jerk_cos", "tracing_jerk_sin"
    ]
    input_lag: null
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 60
  dbs_condition: "both"
  jitter: 0

results:
  save_dir: "results/{model.name}"
  log_dir: "{results.save_dir}/logs"
  checkpoint_dir: "checkpoints"
