model:
  name: psid_behavioral_PDI1_2_nx_40_n4_i80_dbs_off_narrow_band
  nx: 40
  n1: 4
  i: 80
  time_first: true
  fast: false
  reuse_splits: false
  alpha_Q: 0.0001
  alpha_R: 0.01
  backward_kalman: true
  rescale_states: true
  max_eigenvalue: 0.995
  forecast:
    m: 2
    history: 5
data:
  root: resampled_recordings/participants_at_80Hz_scaled_1e6_narrow_band
  participant: PDI1
  session: '2'
  blocks: all
  channels:
    neural_input:
    - ECOG_3_delta_raw
    - ECOG_2_delta_raw
    - ECOG_1_delta_raw
    - ECOG_4_delta_raw
    - ECOG_3_highbeta_raw
    - ECOG_2_highbeta_raw
    - LFP_10_delta_raw
    - ECOG_4_highbeta_raw
    - ECOG_4_beta_raw
    - LFP_9_highbeta_raw
    - LFP_10_highbeta_raw
    - LFP_12_highbeta_raw
    - ECOG_3_beta_raw
    - LFP_11_highbeta_raw
    - LFP_13_delta_raw
    - LFP_14_highbeta_raw
    - LFP_13_highbeta_raw
    - LFP_16_highbeta_raw
    - LFP_15_highbeta_raw
    - LFP_16_delta_raw
    output_type: behavioral
    output:
    - tracing_velocity_y
    - tracing_velocity_magnitude
    - tracing_jerk_x
    - tracing_jerk_magnitude
    input_lag: null
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 80
  dbs_condition: 'off'
  jitter: 0
results:
  save_dir: results/{model.name}
  log_dir: '{results.save_dir}/logs'
  checkpoint_dir: checkpoints
