model:
  name: psid_grid_search_PDI1_S2_log_power_part_2
  i: 80
  time_first: true
  reuse_splits: true
  forecast:
    m: 2
    history: 5
  grid_search:
    nx:
    - 15
    - 25
    - 30
    - 35
    - 40
    - 45
    n1:
    - 4
    - 0.0001
    - 0.01
    backward_kalman:
    - true
    rescale_states:
    - true
    max_eigenvalue:
    - 0.995
    neural_bands:
    - - ECOG_3_delta_log_power
      - ECOG_2_delta_log_power
      - ECOG_1_delta_log_power
      - ECOG_4_delta_log_power
      - ECOG_3_highbeta_log_power
      - ECOG_2_highbeta_log_power
      - LFP_10_delta_log_power
      - ECOG_4_highbeta_log_power
      - ECOG_4_beta_log_power
      - LFP_9_highbeta_log_power
      - LFP_10_highbeta_log_power
      - LFP_12_highbeta_log_power
      - ECOG_3_beta_log_power
      - LFP_11_highbeta_log_power
      - LFP_13_delta_log_power
      - LFP_14_highbeta_log_power
      - LFP_13_highbeta_log_power
      - LFP_16_highbeta_log_power
      - LFP_15_highbeta_log_power
      - LFP_16_delta_log_power
    behavioral_outputs:
    - - tracing_velocity_y
      - tracing_velocity_magnitude
      - tracing_jerk_x
      - tracing_jerk_magnitude
data:
  root: resampled_recordings/participants_at_80Hz_scaled_1e6_log
  participant: PDI1
  session: '2'
  blocks: all
  channels:
    neural_input:
    - ECOG_1_beta_log_power
    - ECOG_2_beta_log_power
    - ECOG_3_beta_log_power
    - ECOG_4_beta_log_power
    output_type: behavioral
    output:
    - tracing_velocity_magnitude
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 80
  dbs_condition: both
results:
  save_dir: results/psid_grid_search_log_power_part_2
  log_dir: '{results.save_dir}/logs'
  checkpoint_dir: checkpoints
