model:
  name: psid_grid_search_PDI2_S4_log_power_part_2
  i: 80
  time_first: true
  reuse_splits: true
  forecast:
    m: 2
    history: 5
  grid_search:
    nx:
    - 20
    - 25
    - 30
    - 35
    - 40
    - 45
    n1:
    - 16
    alpha_Q:
    - 0.001
    alpha_R:
    - 0.01
    backward_kalman:
    - true
    rescale_states:
    - true
    max_eigenvalue:
    - 0.995
    neural_bands:
    - - ECOG_2_highbeta_log_power
      - ECOG_1_highbeta_log_power
      - ECOG_3_highbeta_log_power
      - ECOG_2_beta_log_power
      - ECOG_3_beta_log_power
      - ECOG_3_lowbeta_log_power
      - ECOG_3_alpha_log_power
      - ECOG_1_beta_log_power
      - LFP_13_delta_log_power
      - ECOG_4_highbeta_log_power
      - ECOG_4_beta_log_power
      - LFP_11_theta_log_power
      - ECOG_2_lowbeta_log_power
      - LFP_12_alpha_log_power
      - LFP_13_theta_log_power
      - LFP_11_delta_log_power
      - LFP_14_theta_log_power
      - LFP_12_delta_log_power
      - LFP_11_alpha_log_power
      - LFP_12_theta_log_power
    behavioral_outputs:
    - - tracing_acceleration_y
      - tracing_acceleration_magnitude
data:
  root: resampled_recordings/participants_at_80Hz_scaled_1e6_log
  participant: PDI2
  session: '4'
  blocks: all
  channels:
    neural_input:
    - ECOG_1_beta_log_power
    - ECOG_2_beta_log_power
    - ECOG_3_beta_log_power
    - ECOG_4_beta_log_power
    output_type: behavioral
    output:
    - tracing_velocity_magnitude
    input_lag: null
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 80
  dbs_condition: both
  jitter: 0
results:
  save_dir: results/psid_grid_search_log_power_part_2
  log_dir: '{results.save_dir}/logs'
  checkpoint_dir: checkpoints
