model:
  name: psid_grid_search_PDI4_S2_log_power_part_1
  i: 80
  time_first: true
  reuse_splits: true
  forecast:
    m: 2
    history: 5
  grid_search:
    nx:
    - 20
    n1:
    - 4
    - 8
    - 12
    - 16
    alpha_Q:
    - 1e-5
    - 1e-4
    - 1e-3
    alpha_R:
    - 1e-3
    - 1e-2
    backward_kalman:
    - true
    rescale_states:
    - true
    max_eigenvalue:
    - 0.995
    neural_bands:
    - - LFP_13_delta_log_power
      - LFP_10_highbeta_log_power
      - LFP_14_delta_log_power
      - ECOG_1_theta_log_power
      - LFP_10_beta_log_power
      - ECOG_1_highbeta_log_power
      - LFP_13_highbeta_log_power
      - LFP_10_delta_log_power
      - LFP_16_theta_log_power
      - ECOG_2_highbeta_log_power
    behavioral_outputs:
    - - tracing_velocity_y
      - tracing_velocity_magnitude
      - tracing_velocity_x
data:
  root: resampled_recordings/participants_at_80Hz_scaled_1e6_log
  participant: PDI4
  session: '2'
  blocks: all
  channels:
    neural_input:
    - ECOG_1_beta_log_power
    - ECOG_2_beta_log_power
    - ECOG_3_beta_log_power
    - ECOG_4_beta_log_power
    output_type: behavioral
    output:
    - tracing_velocity_magnitude
    input_lag: null
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 80
  dbs_condition: both
  jitter: 0
results:
  save_dir: results/psid_grid_search_log_power_part_1
  log_dir: '{results.save_dir}/logs'
  checkpoint_dir: checkpoints
