model:
  name: psid_laplacian_PDI4_2_nx_60_n7_i100_dbs_on_200Hz_narrow_band_mrmr8
  nx: 60
  n1: 7
  i: 100
  time_first: true
  fast: false
  reuse_splits: false
  max_eigenvalue: 0.9999
  forecast:
    m: 1
    history: 3
data:
  root: resampled_recordings/participants_at_200Hz_scaled_1e6_narrow_band
  participant: PDI4
  session: '2'
  blocks: all
  channels:
    neural_input:
    - ECOG_4_theta_4_8_raw
    - ECOG_4_beta_12_17_raw
    - ECOG_4_gamma_75_80_raw
    - ECOG_2_beta_17_22_raw
    - ECOG_3_gamma_70_75_raw
    - ECOG_3_beta_12_17_raw
    - ECOG_3_theta_4_8_raw
    - ECOG_1_alpha_8_12_raw
    output_type: neural
    output:
    - LAPLACIAN_14-16_LFP_theta_4_8_raw
    - LAPLACIAN_14-16_LFP_beta_12_17_raw
    - LAPLACIAN_14-16_LFP_beta_27_30_raw
    - LAPLACIAN_14-16_LFP_gamma_45_50_raw
    - LAPLACIAN_14-16_LFP_gamma_75_80_raw
    - LAPLACIAN_14-16_LFP_beta_17_22_raw
    - LAPLACIAN_14-16_LFP_alpha_8_12_raw
    - LAPLACIAN_14-16_LFP_gamma_60_65_raw
  split:
    within_session_split: true
  batch_size: 32
  sampling_frequency: 200
  dbs_condition: 'on'
results:
  save_dir: results/psid_laplacian_PDI4_2_nx_60_n7_i100_dbs_on_200Hz_narrow_band_mrmr8
  log_dir: results/psid_laplacian_PDI4_2_nx_60_n7_i100_dbs_on_200Hz_narrow_band_mrmr8/logs
  checkpoint_dir: checkpoints
