model:
  name: dpad_laplacian_PDI1_2_nx_75_n10_e3000_mrmr8_dbs_both_200Hz_narrow_band
  nx: 75
  n1: 10
  method_code: DPAD_uAKCzCy2HL32U
  epochs: 3000
  fast: true
  reuse_splits: true
  checkpoint_every: 100
  steps_ahead:
  - 1
  steps_ahead_loss_weights:
  - 1.0
  forecast:
    m: 2
    history: 5
data:
  root: resampled_recordings/participants_at_200Hz_scaled_1e6_narrow_band
  participant: PDI1
  session: '2'
  blocks: all
  channels:
    neural_input:
    - ECOG_3_beta_12_17_raw
    - ECOG_3_beta_17_22_raw
    - ECOG_2_beta_12_17_raw
    - ECOG_2_beta_17_22_raw
    - ECOG_4_beta_12_17_raw
    - ECOG_4_beta_17_22_raw
    - ECOG_3_theta_4_8_raw
    - ECOG_3_beta_22_27_raw
    output_type: neural
    output:
    - LAPLACIAN_14-16_LFP_theta_4_8_raw
    - LAPLACIAN_14-16_LFP_beta_12_17_raw
    - LAPLACIAN_14-16_LFP_beta_27_30_raw
    - LAPLACIAN_14-16_LFP_gamma_70_75_raw
    - LAPLACIAN_14-16_LFP_gamma_45_50_raw
    - LAPLACIAN_14-16_LFP_alpha_8_12_raw
    - LAPLACIAN_14-16_LFP_beta_17_22_raw
    - LAPLACIAN_14-16_LFP_gamma_35_40_raw
  split:
    within_session_split: true
  batch_size: 32
  sampling_frequency: 200
  dbs_condition: both
results:
  save_dir: results/dpad_laplacian_PDI1_2_nx_75_n10_e3000_mrmr8_dbs_both_200Hz_narrow_band
  log_dir: results/dpad_laplacian_PDI1_2_nx_75_n10_e3000_mrmr8_dbs_both_200Hz_narrow_band/logs
  checkpoint_dir: checkpoints
