model:
  name: psid_behavioral_PDI4_3_nx_25_n6_i40_vanilla_dbs_both_200Hz_narrow_band
  nx: 25
  n1: 6
  i: 40
  time_first: true
  fast: false
  reuse_splits: false
  backward_kalman: false
  rescale_states: false
  max_eigenvalue: 0.999
  forecast:
    m: 2
    history: 5
data:
  root: resampled_recordings/participants_at_200Hz_scaled_1e6_narrow_band
  participant: PDI4
  session: '3'
  blocks: all
  channels:
    neural_input:
    - ECOG_1_theta_4_8_raw
    - ECOG_1_alpha_8_12_raw
    - ECOG_1_beta_12_17_raw
    - ECOG_1_beta_17_22_raw
    - ECOG_1_beta_22_27_raw
    - ECOG_1_beta_27_30_raw
    - ECOG_1_gamma_30_35_raw
    - ECOG_1_gamma_35_40_raw
    - ECOG_1_gamma_40_45_raw
    - ECOG_1_gamma_45_50_raw
    - ECOG_1_gamma_50_55_raw
    - ECOG_1_gamma_55_60_raw
    - ECOG_1_gamma_60_65_raw
    - ECOG_1_gamma_65_70_raw
    - ECOG_1_gamma_75_80_raw
    - ECOG_2_theta_4_8_raw
    - ECOG_2_alpha_8_12_raw
    - ECOG_2_beta_12_17_raw
    - ECOG_2_beta_17_22_raw
    - ECOG_2_beta_22_27_raw
    - ECOG_2_beta_27_30_raw
    - ECOG_2_gamma_30_35_raw
    - ECOG_2_gamma_35_40_raw
    - ECOG_2_gamma_40_45_raw
    - ECOG_2_gamma_45_50_raw
    - ECOG_2_gamma_50_55_raw
    - ECOG_2_gamma_55_60_raw
    - ECOG_2_gamma_60_65_raw
    - ECOG_2_gamma_65_70_raw
    - ECOG_2_gamma_75_80_raw
    - ECOG_3_theta_4_8_raw
    - ECOG_3_alpha_8_12_raw
    - ECOG_3_beta_12_17_raw
    - ECOG_3_beta_17_22_raw
    - ECOG_3_beta_22_27_raw
    - ECOG_3_beta_27_30_raw
    - ECOG_3_gamma_30_35_raw
    - ECOG_3_gamma_35_40_raw
    - ECOG_3_gamma_40_45_raw
    - ECOG_3_gamma_45_50_raw
    - ECOG_3_gamma_50_55_raw
    - ECOG_3_gamma_55_60_raw
    - ECOG_3_gamma_60_65_raw
    - ECOG_3_gamma_65_70_raw
    - ECOG_3_gamma_75_80_raw
    - ECOG_4_theta_4_8_raw
    - ECOG_4_alpha_8_12_raw
    - ECOG_4_beta_12_17_raw
    - ECOG_4_beta_17_22_raw
    - ECOG_4_beta_22_27_raw
    - ECOG_4_beta_27_30_raw
    - ECOG_4_gamma_30_35_raw
    - ECOG_4_gamma_35_40_raw
    - ECOG_4_gamma_40_45_raw
    - ECOG_4_gamma_45_50_raw
    - ECOG_4_gamma_50_55_raw
    - ECOG_4_gamma_55_60_raw
    - ECOG_4_gamma_60_65_raw
    - ECOG_4_gamma_65_70_raw
    - ECOG_4_gamma_75_80_raw
    output_type: behavioral
    output:
    - tracing_velocity_x
    - tracing_acceleration_magnitude
  split:
    within_session_split: true
    train: 0.6
    val: 0.1
    test: 0.3
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 200
  dbs_condition: both
results:
  save_dir: results/psid_behavioral_PDI4_3_nx_25_n6_i40_vanilla_dbs_both_200Hz_narrow_band
  log_dir: results/psid_behavioral_PDI4_3_nx_25_n6_i40_vanilla_dbs_both_200Hz_narrow_band/logs
  checkpoint_dir: checkpoints
