model:
  name: psid_behavioral_PDI2_2_nx_25_n8_i80_dbs_on_log_power
  nx: 25
  n1: 8
  i: 80
  time_first: true
  fast: false
  reuse_splits: false
  alpha_Q: 1.0e-05
  alpha_R: 0.01
  backward_kalman: true
  rescale_states: true
  max_eigenvalue: 0.995
  forecast:
    m: 2
    history: 5
data:
  root: resampled_recordings/participants_at_80Hz_scaled_1e6_log
  participant: PDI2
  session: '2'
  blocks: all
  channels:
    neural_input:
    - ECOG_3_highbeta_log_power
    - ECOG_4_highbeta_log_power
    - ECOG_4_lowbeta_log_power
    - ECOG_4_theta_log_power
    - ECOG_4_beta_log_power
    - ECOG_3_beta_log_power
    - ECOG_3_lowbeta_log_power
    - LFP_11_delta_log_power
    - ECOG_4_alpha_log_power
    - ECOG_3_alpha_log_power
    - LFP_15_lowbeta_log_power
    - LFP_12_lowbeta_log_power
    - LFP_13_beta_log_power
    - LFP_11_lowbeta_log_power
    - ECOG_2_highbeta_log_power
    - LFP_14_beta_log_power
    - LFP_9_beta_log_power
    - LFP_15_delta_log_power
    - LFP_10_beta_log_power
    - LFP_16_beta_log_power
    output_type: behavioral
    output:
    - tracing_velocity_x
    - tracing_acceleration_y
    - tracing_acceleration_magnitude
    - tracing_jerk_y
    - tracing_jerk_magnitude
    input_lag: null
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 80
  dbs_condition: 'on'
  jitter: 0
results:
  save_dir: results/{model.name}
  log_dir: '{results.save_dir}/logs'
  checkpoint_dir: checkpoints
